export const data = {
    delaware: [
        {
            day: 1,
            name: "Delaware",
            date: 'August 10, 2024',
            description: 'Left home at 5am, reached bethany house at 9:30am. Road trip was nice, had to stop twice to get charge. Once I reached everyone was slowly getting up. We rushed to the boat dock and hopped on the boat. The festivities began and we had to dodge all the sand bars. We stopped in this muddy area but after a little bit everyone said fuck it and hopped in. On the way back we went to the actual sand bar and hung out over there. Went back to the house, showered and then left for Secrets. That place was fun, so many different areas - live music, EDM, club, would defintely go back. Had to deal with some friend drama at the end of the night LOL',
            image: '/images/delBoat.jpg',
            category: 'Beach',
        },
        {
            day: 2,
            date: 'August 11, 2024',
            name: "Delaware",
            description: 'Woke up pretty early, got ready and left at 11am. Got Dunkin w the group and then hit the road with Akriti and Hari. Good to have company at least one of the ways. Screaming PIGEON the whole way back. Got home at 5:30 because of the hr charging wait at Wilimgton. Screw electric cards for long drives',
            image: '/images/delcar.jpg',
            category: 'Travel'
        },
    ],
    india24: [
        {
            day: 1,
            date: 'July 3, 2024',
            description: 'Dada dropped me off at EWR. United flight at 9pm was pretty nice. I had aisle seat but the Indian lady screwed me over and I got a middle seat between a dada and a chill dude. Talked to chill dude for a while. Indian flight attendant was funny. Popped melatonin and got a little bit of sleep',
            image: '/images/eiffel-tower.jpg',
            category: "Travel",
        },
        {
            day: 2,
            date: 'July 4, 2024',
            description: 'Landed in Delhi. Last 6 hours was the hardest. Got to see Himalayas on the way in. Landed in Delhi, immigration was fast. I couldnt check into my connection so I had 7 hrs to burn. I went to the transfer lounge for a bit and then I had to leave. Walked around for a bit and realised theres nothing to do. I checked hotels outside but there was small hotel rooms in the airport. So I paid 4500 rupees for 3 hrs and knocked out. FTed a few people and left and checked in. Security was fast and went to the amex lounge which had some of the best chai ive had. Screw south indian food in the morning tho',
            image: '/images/louvre.jpg',
            category: "Travel",
        },
        {
            day: 3,
            date: 'July 5, 2024',
            description: 'Went to the gate, took a bus to the Vistara plane. Service was amazing but I did have the last seat on the plane. Landed in Ahmedabad. Bags came out fast and went to Ba and Dadas. They were excited to see me but I was met with my mom who had a laundry list of thins for me to do. Tried on a bunch of Jabhas, went shopping and got dinner with Natu data at 635. Knocked out and got ready for the early morning flight',
            image: '/images/versailles.jpg',
            category: "Shopping",
        },
        {
            day: 4,
            date: 'July 6, 2024',
            description: 'Woke up and went to the airport at 8am. Met the homies at the airport. Plane was delayed 3 hrs, screw you SpiceJet! We flew on some plane they bought from a Chinese airline was worried for my life. Landed at Ayodhya airport which was designed really nicely and had a cool touch to hinduism. Found the bus Chappaiya, had to load the bags at the top of the bus to fit and most our bags got wet. Tree fell on the way there because of the downpour. Driver didnt know where to drop us off but finally we got off and we were greeted to some umbrellas. The place was awesome, literally like a hotel. We got to our room and then quickly headed out for aarti and dinner. We walked in knee deep water to get around, it was rough. After eating we were summmoned to Lalji Maharajs room. Hung out with him and met the India crew then knocked out',
            image: '/images/versailles.jpg',
            category: "Travel",
        },
        {
            day: 5,
            date: 'July 7, 2024',
            description: 'Woke up early, missed aarti tho. Got ready in those 5 star showers. Did darshan and went to the eating area. Eating in that area in the steel dishes and sitting on the plastic chairs really makes you feel like a local. Did a walk around the saryu. Hung out in Lalji Maharajs room for a bit, had froggy and Choksi sit next to each other. We then headed in the car to Ram Mandir. Messed with Leo on the way there. So many rows of lines and checkpoints to enter. We finally got into line and got a quick 2 min darshan. The architecture is beautiful and the history with the Muslim Mosque before is fasinating. So many flies around, we got back, got our shoes and left. Headed back with LM and got corn on the way back. Saw the saryu at night for the first time and that was beautiful',
            image: '/images/versailles.jpg',
            category: "Sightseeing",
        },
        {
            day: 6,
            date: 'July 8, 2024',
            description: 'Woke up and did the same - darshan, breakfast, chill with LM. Choksi and LM did face masks and we got him ready for the first event - tilak. We couldnt enter the tilak stuff but at the end everyone came out to do Darshan and there was the smoke fireworks in the air and the dhols were out. Sat on the dhol for the first time and dances so much I was sweating all over. Had an amazing time with the boys. Showered up and went to mandir to sing dhun for podhanyu. Mid podhanyu we realised that they were all dancing outside the hall and LM was waiting for us. We ran over and joined. Dances only to the dhol and sweat right thru the jabha. Got LM and AM and dad in the circle, everyone was having a great time. Had a huge dinner in the new wedding hall (literally all types of food) ',
            image: '/images/versailles.jpg',
            category: "Wedding",
        },
        {
            day: 7,
            date: 'July 9, 2024',
            description: 'Woke up and did the same - darshan, breakfast, chill with LM. Today was the Sangeet day so we praciticed extra hard for the dance. Prolly had the best performance cant lie. Had to do a dance/game with AJ because of AM. ',
            image: '/images/versailles.jpg',
            category: "Wedding",
        },
        {
            day: 8,
            date: 'July 10, 2024',
            description: 'Woke up and did the same - darshan, breakfast, chill with LM. Today was Haldi day. We couldnt go until the end but once we got there it was madness. Slapped some haldi and water on this face. After everyone was ripping everyones jabho (still have mine lol). It was a fun memory. After we got cleaned up, had some maggi and went to the chatris with Saumya and AJ. Walked around Saryu with LM, we could tell he was nervous. He had the mendhi night and we just waited so they could enjoy. LM wrote AJ with a heart on my hand, better than what he wrote on others LOL.  LM tried making us come over at night and had to blame us not going on Choksis explosive poop',
            image: '/images/versailles.jpg',
            category: "Wedding",
        },
        {
            day: 9,
            date: 'July 11, 2024',
            description: '',
            image: '/images/versailles.jpg',
            category: "Wedding",
        },

    ],
    irelandScotland : [
        {
          day: 1,
          name: "Flight to Dublin",
          date: 'June 13, 2024',
          description: 'Got dropped off at Haris, took an Uber from there to JFK. T4 TSA sucked and took longer. No louges would take priority pass at our time (prime time) so we waited for Air India lounge. After 30 mins we got in and ate up. Boarded the 767, we were 3 seats from the back but we all got to sit next to each other. Service was really nice om the plane and Hari was awake to keep me company. Started titanic and knocked out in the middle',
          image: '/images/irelandScotland/sas.JPG',
          category: 'Travel',
        },
        {
          day: 2,
          name: "Dublin exploring",
          date: 'June 14, 2024',
          description: 'Landed in Dublin, got our bags, exchanged some cash and caught an Uber to the hotel. Uber driver smelled like cigs and looked like hes been through hella packs in his day. Got to the hotel, freshed up and went to get breakfast - had a fancy english style food. Then went to explore Trinity College (we found College Park). Walked around the main downtown and then went across the river to the Jamison Distillery. Seeing the history and the area where it all started was pretty cool. Then we headed to the Guiness Factory that had several stories and each of them had a cool experience showing a part of the brewing process. At the top there was a obervation deck and had my first Guiness. Walked around until our reservation at the italian place. There was two groups and only one chef but probably the best italian food ive had. Headed out to temple bar area with a full stomach and ended the night with some mediterranian fast food',
          image: '/images/irelandScotland/jamison.JPG',
          category: 'Sightseeing',
        },
        {
          day: 3,
          name: "Belfast Tour",
          date: 'June 15, 2024',
          description: 'Woke up 5am got ready and left to Belfast Tour Bus. Stopped at some ruined castle near the water and then the hexagonal stone structures near the water. Crazy how they look so perfect and are a natural wonder. The way to and from there was beautiful. Walking along the cliff, one side is the steep dive down into the atlantic, the other side with herds of sheep and goat. Stooped at a tree structure from GOT which looked unusual. Last stop was Belfast city which seemed like more of a modern city with newer buildings and structures. The tour guide was telling us of the issues between Northern Ireland and Ireland because of the religion and idealogies. Hari was chatting up the person next to him. Told the bus driver he looked like the guy from Are We Done Yet',
          image: '/images/irelandScotland/belfastCliffs.JPG',
          category: 'Sightseeing',
        },
        {
          day: 4,
          name: "Cliffs of Moher Tour",
          date: 'June 16, 2024',
          description: 'Another 6am morning. Got up and straight to the bus. Slept on the bus there but once we got there, there was so many people. Walked along these huge Cliffs and saw them on both sides. Tried to spot the penguin looking birds. Went to this area with huge stones leading almost a mile into the land, seeing how far it went down looks surreal. Stopped by Galway which was a fun litle down with 4 busy alleys of shops and food. Long drive back and then got Sushi and noodles for dinner. Went to the oldest pub in Dublin (12th Century)',
          image: '/images/irelandScotland/moherCliffs.JPG',
          category: 'Sightseeing',
        },
        {
          day: 5,
          name: "Welcome Edinburgh",
          date: 'June 17, 2024',
          description: 'Woke up early to catch Ryanair flight to Edinburgh. Ryanairs plastic seats made me appreciate Spirit, but not bad for $40. Landed in an hour. Edinburgh was a cool medieval town with a huge castle in the middle looking above the rest of the town. Walked around town to the main church, Trinity st, Scott Monument. Everywhere you went you got a different glimpse of the castle. Went to a bar that had a noose that the used to hang over 100 people in the square in front of our hotel. We also went to a bar where the most dangerous people back in the day would hang out',
          image: '/images/irelandScotland/edinburgh.JPG',
          category: 'Sightseeing',
        },
        {
          day: 6,
          name: "Scottish Highlands",
          date: 'June 18, 2024',
          description: '10am bus to Scottish Highlands. Stopped in a cute small town for breakfast and then saw some coo and fed them. Sat frontseat in the bus which gave some awesome views of the highalnds. Two way road disecting a bunch of small mountains with the fog running through them. Saw some landmarks from Harry Potter and GOT. Stopped in Fort Augustus to have some cheap Chinese food and take the Lochness cruise. My jeans got fully wet but the Lochness was huge and in the center of a bus of mountains. Tried some scotch ice cream and it was delicious. Got back and it was a struggle finding dinner so we settled for some KFC. Visited the Black Cat and a few other places. ',
          image: '/images/irelandScotland/highlands.JPG',
          category: 'Sightseeing',
        },
        {
          day: 7,
          name: "Edinburgh Exploring",
          date: 'June 19, 2024',
          description: 'Got breakfast at this local place and the english tea was nice. Visted the illusion museum which I thought would be a waste of time but was really cool. Trippy as hell. Got lunch at Dishoom - the apps were better than the main. Climbed up to the castle which had amazing views of the city. Saw where they kept people in jail and how they would protect the castle. Then we hiked up Arthurs Seat which took us about an hour (because at that point weve been eating really unhealthy and were not in shape. We had to stop 3-4 times and I was lugging around a backpack. Finally made it and had some crazy view of the city but it was so windy. Headed back down and then to the hotel. Went to the Johnnie Walker Michellin Experience. Meals were really good. The lady we met from Brazil was so weird she kept asking if there was discounts on the drinks. We hung out with the staff after closing. Sunset from there was spectacular. Ended the day at Black Cat and got Taco Bell after',
          image: '/images/irelandScotland/arthurseat.JPG',
          category: 'Sightseeing',
        },
        {
          day: 8,
          name: "Back Home",
          date: 'June 20, 2024',
          description: 'Ryanair back to Dublin. They said mine and Rits bag was too big so they made us pay 80 euros each. Landed in Dublin, got our bags and rechecked them into our Delta flight back. Again we were in the back of the plane but got to sit next to each other. Landed in JFK and ubered back home',
          image: '/images/irelandScotland/ryanair.JPG',
          category: 'Travel',
        },
    
      ]
}